vim.cmd.packadd("nvim.undotree")
vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv")
vim.keymap.set("v", "K", ":m '<-2<CR>gv=gv")
vim.keymap.set("n", "J", "mzJ`z")
vim.keymap.set("n", "<C-d>", "<C-d>zz")
vim.keymap.set("n", "<C-u>", "<C-u>zz")
vim.keymap.set("n", "n", "nzzzv")
vim.keymap.set("n", "N", "Nzzzv")
vim.keymap.set("x", "<leader>p", [["_dP]])
vim.keymap.set({ "n", "v" }, "<leader>y", [["+y]])
vim.keymap.set("n", "<leader>Y", [["+Y]])
vim.keymap.set({ "n", "v" }, "<leader>d", '"_d')
vim.keymap.set("n", "<leader>s", [[:%s/\<<C-r><C-w>\>/<C-r><C-w>/gI<Left><Left><Left>]])
vim.keymap.set("n", "<leader>gs", "<cmd>Git<CR>")
vim.keymap.set("n", "<leader>u", "<cmd>Undotree<CR>")
vim.keymap.set("n", "<C-Up>", ":resize -1<CR>", { noremap = true, silent = true })
vim.keymap.set("n", "<C-Down>", ":resize +1<CR>", { noremap = true, silent = true })
vim.keymap.set("n", "<C-Right>", ":vertical resize +1<CR>", { noremap = true, silent = true })
vim.keymap.set("n", "<C-Left>", ":vertical resize -1<CR>", { noremap = true, silent = true })
vim.keymap.set("i", "jk", "<ESC>", { noremap = true, silent = true })
vim.keymap.set("n", "<c-k>", "<cmd>wincmd k<CR>")
vim.keymap.set("n", "<c-j>", "<cmd>wincmd j<CR>")
vim.keymap.set("n", "<c-h>", "<cmd>wincmd h<CR>")
vim.keymap.set("n", "<c-l>", "<cmd>wincmd l<CR>")
vim.keymap.set("n", "<leader>a", function()
  vim.cmd("$argadd %")
  vim.cmd("argdedup")
end)
vim.keymap.set("n", "<C-e>", "<cmd>args<CR>")
vim.keymap.set("n", "<leader>h", "<cmd>silent! 1argument<CR>")
vim.keymap.set("n", "<leader>j", "<cmd>silent! 2argument<CR>")
vim.keymap.set("n", "<leader>k", "<cmd>silent! 3argument<CR>")
vim.keymap.set("n", "<leader>l", "<cmd>silent! 4argument<CR>")
