set -g prefix C-s
unbind C-b
bind C-s send-prefix

set -g base-index 1
setw -g pane-base-index 1

setw -g mode-keys vi
set -g status-position top
set -g status-justify absolute-centre
set -g status-style "bg=default"
set -g window-status-current-style "fg=blue bold"
set -g window-status-style "fg=white bg=default"
set -g renumber-windows on
set -a terminal-features "tmux-256color:RGB"
set -ga terminal-overrides ",*:Tc"
set -g window-status-separator ""
set -g window-status-format "#[fg=colour240]#[default] #I:#W#{?window_flags,#{window_flags},} #[fg=colour240]#[default]"
set -g window-status-current-format "#[fg=colour252]#[default] #I:#W#{?window_flags,#{window_flags},} #[fg=colour252]#[default]"
set -g status-interval 5
set -g status-left "#S"
set -g status-right ""

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
bind x kill-window
bind p run "tmux neww -c '#{pane_current_path}' -n pdf 'pdf'"
bind g run "open-repo"
bind l run "ts ~/dotfiles"
bind H display-popup -E -w 80% -h 80% "ts"
unbind k
unbind s
unbind S
unbind T
bind G neww -n "git" -S lazygit
bind y neww -n "yazi" -S yazi 
bind W run "tmux neww -n work-mode 'work-mode toggle; printf \"\\nPress enter to close... \"; read -r _'"
